spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: prod
server:
  port: 8080

cloudinary:
  cloud-name: dwyriyoil
  api-key: 172474118988483
  api-secret: b-P6NHWLTPrR1qd7sXL0daLNowI
